### ISSUE TITLE
Data input structure

### ISSUE THREAD

**Issue by antortjim** [milanXpetrovic/drosophila-social-network-analysis#3]
Dear @milanXpetrovic 

This module looks very promising and I am going to try to use it for my project too, to quantify SINs :). Could you provide a quick overview of how the input data to this package should be organized? i.e. what columns are needed (x, y, id, etc), in what format (.xlsx, .csv, etc), where they should be stored, etc.

Thank you in advance!
Antonio

**Comment by antortjim** [comment]
From this line
https://github.com/milanXpetrovic/drosophila-social-network-analysis/blob/main/src/1_data/0_1_preproc_data.py#L48C44-L48C58 and the `0_0_0_get_csv_from_xlsx.py` module, I think I need to have 1 .xlsx file per experiment, on each one sheet per fly of the experiment, with columns `pos_x` `pos_y` `ori` and  `major axis len`. `ori` needs to have the orientation in radians, and `pos_x` `pos_y` the coordinates of the animal centroid I suppose, in pixels starting from the top left corner. But I am not sure about the content of `major axis len`.

**Comment by antortjim** [comment]
Correct me if I am wrong, but `major axis len` actually is the length of the fly (along its longest axis ie. head->abdomen) in the same units as `pos x` and `pos y`? i.e. it is the body length of the fly.

**Comment by milanXpetrovic** [comment]
Dear @antortjim, I will reply to all three comments here.
The module is currently being developed by me and I am constantly updating it. So you can expect some changes. But the main part will not be changed.
The way the module works is that you input your tracked trajectories of the fruit flies that you track. I organise the data so that I have a folder for the treatment where there are several groups and each group consists of a certain number of flies. I always have the same number of flies in all groups. So you should create a folder `./data` and add a treatment with groups in it.
The module works with .csv data output by the Flytracker software. I have also added a script that converts the data from `.xlsx` to `.csv`. I think it should also work with Ctrax data, but I have not tried it yet.

Yes, for the script `0_0_0_get_csv_from_xlsx.py` you need 1 .xlsx file per experiment, one sheet per fly of the experiment.main `axis len` is the length of the fly on the longer axis, yes. Further information can be found here https://kristinbranson.github.io/FlyTracker/documentation.html

Yes, `major axis len`, `pos x` and `pos y` are in the same units. I use the script `0_0_get_normalization.py` to convert them to `mm`.

**Comment by antortjim** [comment]
Dear @milanXpetrovic sorry for my delayed reply. Of course, I understand you are still developing and some things may need to be done differently. Thanks for getting back with so much detail, it's more clear now. Right now my focus is not on quantifying networks, but I hope to soon try it out. Thanks again!
